// This file defines the bytecode instruction set for the Hython VM.
// The VM is stack-based and CPython-inspired: operands are pushed onto a value stack,
// and instructions consume and produce values from that stack.
//
// Code is organized into CodeObjects — one per module, function, lambda, or class body.
// Jump targets use integer label IDs that are resolved to flat instruction indices
// by the Compiler after each CodeObject is fully emitted.
package paopao.hython;

import paopao.hython.Ast;

enum OpCode {
	// Stack Manipulation
	// Discard the top-of-stack value.
	POP_TOP;

	// Duplicate the top-of-stack value.
	DUP_TOP;

	// Swap TOS and TOS1.
	ROT_TWO;

	// Lift TOS to TOS2 position: TOS2 ← TOS, TOS1 ← TOS2, TOS ← TOS1.
	ROT_THREE;

	// No operation (compiled from `pass`).
	NOP;

	// Load / Store
	// Push a constant value onto the stack.
	LOAD_CONST(value:ConstValue);

	// Push the value of a name looked up through the scope chain.
	LOAD_NAME(name:String);

	// Pop TOS and bind it to `name` in the current scope.
	STORE_NAME(name:String);

	// Push the value of a local variable (used inside functions).
	LOAD_FAST(name:String);

	// Pop TOS and bind it to a local variable (used inside functions).
	STORE_FAST(name:String);

	// Push the value of a module-level name.
	LOAD_GLOBAL(name:String);

	// Pop TOS and bind it to a module-level name.
	STORE_GLOBAL(name:String);

	// Attribute / Subscript
	// TOS = getattr(TOS, attr)
	LOAD_ATTR(attr:String);

	// setattr(TOS1, attr, TOS); pop both.
	STORE_ATTR(attr:String);

	// TOS = TOS1[TOS]; pop both.  (obj[index])
	BINARY_SUBSCR;

	// TOS1[TOS] = TOS2; pop all three.
	STORE_SUBSCR;

	// Operators
	// Pop TOS and TOS1, push TOS1 <op> TOS.
	BINARY_OP(op:BinOp);

	// Pop TOS, push <op> TOS.
	UNARY_OP(op:UnaryOp);

	// Collection Builders
	// Pop `count` items (bottom-to-top order), push a new list.
	BUILD_LIST(count:Int);

	// Pop `count` items, push a new tuple.
	BUILD_TUPLE(count:Int);

	// Pop `count` key/value pairs (key pushed first), push a new dict.
	BUILD_DICT(count:Int);

	// Pop `count` items into a list, then push [rest...] for unpacking.
	// (Used for starred unpacking — reserved for future use.)
	UNPACK_SEQUENCE(count:Int);

	// Functions
	// Push a callable wrapping the given CodeObject onto the stack.
	MAKE_FUNCTION(code:CodeObject);

	// Call TOS with the top `argc` stack values as positional arguments.
	// Pops func + args; pushes return value.
	CALL_FUNCTION(argc:Int);

	// Pop TOS and return it from the current frame.
	RETURN_VALUE;

	// Iterators
	// Replace TOS with iter(TOS).
	GET_ITER;

	// Advance iterator TOS.  On StopIteration jump to `label`; otherwise
	// push the next value (iterator stays on stack beneath the value).
	FOR_ITER(label:Int);

	// Jumps
	// Unconditional jump to `label`.
	JUMP_ABSOLUTE(label:Int);

	// Unconditional jump to `label` (forward-only alias, identical semantics).
	JUMP_FORWARD(label:Int);

	// Pop TOS; jump to `label` if TOS is falsy.
	POP_JUMP_IF_FALSE(label:Int);

	// Pop TOS; jump to `label` if TOS is truthy.
	POP_JUMP_IF_TRUE(label:Int);

	// Loop Control
	// Mark the start of a loop block; `afterLabel` is the exit target.
	SETUP_LOOP(afterLabel:Int);

	// Exit the innermost loop / exception block cleanly.
	POP_BLOCK;

	// Compiled from `break` — unwinds to the enclosing SETUP_LOOP exit.
	BREAK_LOOP;

	// Compiled from `continue` — jumps back to the loop header.
	CONTINUE_LOOP(loopStart:Int);

	// Exception Handling
	// Push an exception-handler block; on exception jump to `handlerLabel`.
	SETUP_EXCEPT(handlerLabel:Int);

	// Push a finally block; on any exit jump to `finallyLabel`.
	SETUP_FINALLY(finallyLabel:Int);

	// Re-raise the active exception (or end a finally block).
	END_FINALLY;

	// Push exc_type, exc_value, traceback onto the stack (handler entry).
	// (Emitted implicitly by the VM; not generated by the compiler directly.)
	// Imports
	// Push the module object for `name` onto the stack.
	IMPORT_NAME(name:String);

	// TOS = getattr(TOS, attr)  — used after IMPORT_NAME for `from … import`.
	IMPORT_FROM(attr:String);

	// Classes
	// Call TOS (the class body function) and wrap the result as a new type.
	// Stack before: [name_str, *bases, body_fn]
	// Stack after:  [class_obj]
	BUILD_CLASS(baseCount:Int);

	// Coroutines / Generators
	// Suspend execution and yield TOS to the caller.
	YIELD_VALUE;

	// Wrap TOS in an awaitable (used by `await` expressions).
	GET_AWAITABLE;

	// Labels (pseudo-instruction)
	// LABEL nodes are inserted during compilation and stripped out by
	// Compiler.resolveLabels(), which rewrites every jump target from a
	// logical label ID to a flat instruction index.
	LABEL(id:Int);
}

// A CodeObject is the compiled representation of one executable unit:
// a module, a function body, a lambda, or a class body.
// After Compiler.resolveLabels() runs, every LABEL pseudo-instruction is
// removed and all jump targets contain absolute instruction indices.
class CodeObject {
	// Human-readable name ("<module>", "<lambda>", function/class name).
	public var name:String;

	// Flat sequence of opcodes (LABELs present during compilation only).
	public var instructions:Array<OpCode>;

	// Ordered parameter names (empty for module / class bodies).
	public var argNames:Array<String>;

	// True when this code object was produced by a `def` marked `async`.
	public var isAsync:Bool;

	// True when the body contains a YIELD_VALUE instruction.
	public var isGenerator:Bool;

	public function new(name:String, argNames:Array<String>, isAsync:Bool = false, isGenerator:Bool = false) {
		this.name = name;
		this.argNames = argNames;
		this.isAsync = isAsync;
		this.isGenerator = isGenerator;
		this.instructions = [];
	}

	// Pretty-print the instruction listing (useful for debugging / tests).
	public function disassemble():String {
		var sb = new StringBuf();
		sb.add('CodeObject <${name}> args=${argNames.join(",")}');
		if (isAsync)
			sb.add(" [async]");
		if (isGenerator)
			sb.add(" [generator]");
		sb.add("\n");

		for (i in 0...instructions.length) {
			sb.add('  ${pad(i, 4)}  ${instrToString(instructions[i])}\n');
		}
		return sb.toString();
	}

	private function pad(n:Int, width:Int):String {
		var s = Std.string(n);
		while (s.length < width)
			s = " " + s;
		return s;
	}

	private function instrToString(op:OpCode):String {
		return switch (op) {
			case POP_TOP: "POP_TOP";
			case DUP_TOP: "DUP_TOP";
			case ROT_TWO: "ROT_TWO";
			case ROT_THREE: "ROT_THREE";
			case NOP: "NOP";

			case LOAD_CONST(v): 'LOAD_CONST        ${constToString(v)}';
			case LOAD_NAME(n): 'LOAD_NAME         ${n}';
			case STORE_NAME(n): 'STORE_NAME        ${n}';
			case LOAD_FAST(n): 'LOAD_FAST         ${n}';
			case STORE_FAST(n): 'STORE_FAST        ${n}';
			case LOAD_GLOBAL(n): 'LOAD_GLOBAL       ${n}';
			case STORE_GLOBAL(n): 'STORE_GLOBAL      ${n}';

			case LOAD_ATTR(a): 'LOAD_ATTR         ${a}';
			case STORE_ATTR(a): 'STORE_ATTR        ${a}';
			case BINARY_SUBSCR: "BINARY_SUBSCR";
			case STORE_SUBSCR: "STORE_SUBSCR";

			case BINARY_OP(op): 'BINARY_OP         ${binOpToString(op)}';
			case UNARY_OP(op): 'UNARY_OP          ${unaryOpToString(op)}';

			case BUILD_LIST(c): 'BUILD_LIST        ${c}';
			case BUILD_TUPLE(c): 'BUILD_TUPLE       ${c}';
			case BUILD_DICT(c): 'BUILD_DICT        ${c}';
			case UNPACK_SEQUENCE(c): 'UNPACK_SEQUENCE   ${c}';

			case MAKE_FUNCTION(co): 'MAKE_FUNCTION     <${co.name}>';
			case CALL_FUNCTION(c): 'CALL_FUNCTION     ${c}';
			case RETURN_VALUE: "RETURN_VALUE";

			case GET_ITER: "GET_ITER";
			case FOR_ITER(l): 'FOR_ITER          >> ${l}';

			case JUMP_ABSOLUTE(l): 'JUMP_ABSOLUTE     >> ${l}';
			case JUMP_FORWARD(l): 'JUMP_FORWARD      >> ${l}';
			case POP_JUMP_IF_FALSE(l): 'POP_JUMP_IF_FALSE >> ${l}';
			case POP_JUMP_IF_TRUE(l): 'POP_JUMP_IF_TRUE  >> ${l}';

			case SETUP_LOOP(l): 'SETUP_LOOP        >> ${l}';
			case POP_BLOCK: "POP_BLOCK";
			case BREAK_LOOP: "BREAK_LOOP";
			case CONTINUE_LOOP(l): 'CONTINUE_LOOP     >> ${l}';

			case SETUP_EXCEPT(l): 'SETUP_EXCEPT      >> ${l}';
			case SETUP_FINALLY(l): 'SETUP_FINALLY     >> ${l}';
			case END_FINALLY: "END_FINALLY";

			case IMPORT_NAME(n): 'IMPORT_NAME       ${n}';
			case IMPORT_FROM(a): 'IMPORT_FROM       ${a}';

			case BUILD_CLASS(b): 'BUILD_CLASS       bases=${b}';

			case YIELD_VALUE: "YIELD_VALUE";
			case GET_AWAITABLE: "GET_AWAITABLE";

			case LABEL(id): '--- LABEL ${id} ---';
		}
	}

	private function constToString(v:ConstValue):String {
		return switch (v) {
			case CInt(n): Std.string(n);
			case CFloat(f): Std.string(f);
			case CString(s): '"${s}"';
			case CBool(b): b ? "True" : "False";
			case CNone: "None";
			case VObject(_): "<object>";
			case VFunction(_): "<native_fn>";
		}
	}

	private function binOpToString(op:BinOp):String {
		return switch (op) {
			case Add: "+";
			case Sub: "-";
			case Mult: "*";
			case Div: "/";
			case Mod: "%";
			case Eq: "==";
			case NotEq: "!=";
			case Lt: "<";
			case Gt: ">";
			case LtE: "<=";
			case GtE: ">=";
			case And: "and";
			case Or: "or";
		}
	}

	private function unaryOpToString(op:UnaryOp):String {
		return switch (op) {
			case Invert: "~";
			case Not: "not";
			case UAdd: "+";
			case USub: "-";
		}
	}
}
